import { Role } from "@prisma/client";

export const PERMISSIONS = {
  ADMIN_ACCESS: "admin.access",
  USERS_MANAGE: "users.manage",
  SETTINGS_MANAGE: "settings.manage",
  LEADS_READ: "leads.read",
  LEADS_WRITE: "leads.write",
  LEADS_ALL: "leads.all",
  PIPELINE: "pipeline.manage",
  FOLLOWUPS: "followups.manage",
  SURVEYS_READ: "surveys.read",
  SURVEYS_WRITE: "surveys.write",
  QUOTATIONS_READ: "quotations.read",
  QUOTATIONS_WRITE: "quotations.write",
  CUSTOMERS_READ: "customers.read",
  CUSTOMERS_WRITE: "customers.write",
  PLANTS: "plants.manage",
  SERVICE: "service.manage",
  AMC: "amc.manage",
  FINANCE: "finance.read",
  REPORTS: "reports.read",
  CONTENT: "content.manage",
  AUDIT: "audit.read",
} as const;

export type Permission = (typeof PERMISSIONS)[keyof typeof PERMISSIONS];

const ALL = Object.values(PERMISSIONS);

const ROLE_PERMISSIONS: Record<Role, Permission[]> = {
  SUPER_ADMIN: ALL,
  ADMIN: ALL,
  SALES_MANAGER: [
    PERMISSIONS.ADMIN_ACCESS,
    PERMISSIONS.LEADS_READ,
    PERMISSIONS.LEADS_WRITE,
    PERMISSIONS.LEADS_ALL,
    PERMISSIONS.PIPELINE,
    PERMISSIONS.FOLLOWUPS,
    PERMISSIONS.SURVEYS_READ,
    PERMISSIONS.SURVEYS_WRITE,
    PERMISSIONS.QUOTATIONS_READ,
    PERMISSIONS.QUOTATIONS_WRITE,
    PERMISSIONS.CUSTOMERS_READ,
    PERMISSIONS.CUSTOMERS_WRITE,
    PERMISSIONS.REPORTS,
  ],
  SALES_EXECUTIVE: [
    PERMISSIONS.ADMIN_ACCESS,
    PERMISSIONS.LEADS_READ,
    PERMISSIONS.LEADS_WRITE,
    PERMISSIONS.FOLLOWUPS,
    PERMISSIONS.SURVEYS_READ,
    PERMISSIONS.SURVEYS_WRITE,
    PERMISSIONS.QUOTATIONS_READ,
    PERMISSIONS.QUOTATIONS_WRITE,
    PERMISSIONS.CUSTOMERS_READ,
  ],
  SITE_SURVEYOR: [
    PERMISSIONS.ADMIN_ACCESS,
    PERMISSIONS.SURVEYS_READ,
    PERMISSIONS.SURVEYS_WRITE,
    PERMISSIONS.LEADS_READ,
  ],
  INSTALLATION_MANAGER: [
    PERMISSIONS.ADMIN_ACCESS,
    PERMISSIONS.CUSTOMERS_READ,
    PERMISSIONS.CUSTOMERS_WRITE,
    PERMISSIONS.PLANTS,
  ],
  SERVICE_MANAGER: [
    PERMISSIONS.ADMIN_ACCESS,
    PERMISSIONS.CUSTOMERS_READ,
    PERMISSIONS.PLANTS,
    PERMISSIONS.SERVICE,
    PERMISSIONS.AMC,
  ],
  FINANCE: [
    PERMISSIONS.ADMIN_ACCESS,
    PERMISSIONS.QUOTATIONS_READ,
    PERMISSIONS.FINANCE,
    PERMISSIONS.REPORTS,
  ],
  VIEWER: [
    PERMISSIONS.ADMIN_ACCESS,
    PERMISSIONS.LEADS_READ,
    PERMISSIONS.CUSTOMERS_READ,
    PERMISSIONS.QUOTATIONS_READ,
    PERMISSIONS.REPORTS,
  ],
};

export function hasPermission(role: Role, permission: Permission) {
  return ROLE_PERMISSIONS[role]?.includes(permission) ?? false;
}
